/**
 *************************************************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 *************************************************************************************************************
 */

#include "Helpers/logger.h"

// Added for project
#include "stm32f4xx.h"

int main(void)
{
	log_info("Program entry point");
	/* Loop forever */
	for(;;);
}
