/**
 *************************************************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 *************************************************************************************************************
 */

#include <stdint.h>

// Added for project
#include "stm32f4xx.h"

int main(void)
{
    /* Loop forever */
	for(;;);
}
